// 100 kuraterede legetøjsmærker relevante for det danske marked
// Inkl. pædagogiske/institutionsmærker + mainstream-favoritter
export const TOY_BRANDS = [
  // Byggeklodser & konstruktion
  'LEGO',
  'LEGO Duplo',
  'Plus-Plus',
  'Magformers',
  'Magna-Tiles',
  'Geomag',
  "K'Nex",
  'Meccano',
  'Clics',
  'Sluban',
  'Mega Bloks',
  'GraviTrax',

  // Figurer, biler & rolleleg
  'Playmobil',
  'Schleich',
  'Bruder',
  'Siku',
  'Barbie',
  'Hot Wheels',
  'Sylvanian Families',
  'Monster High',
  'Maileg',
  'Lilliputiens',
  'Le Toy Van',
  'Our Generation',
  'Disney',
  'Paw Patrol',
  'Gurli Gris (Peppa Pig)',
  'Pokémon',

  // Tog & bevægelse
  'BRIO',
  'Moover',
  'Viking Toys',
  'BERG',

  // Pædagogisk & sansemotorik (institution)
  'ABC Leg',
  'Bolden',
  'Gonge',
  'Pirana',
  'Wesco',
  'Wonderworld',
  'Educo',
  'Edx Education',
  'Learning Resources',
  'TickiT',
  'Numicon',
  'Miniland',
  'Time Timer',
  'Tangle',
  'Koko-Nora',
  'Hugimals',
  'Wobbel',
  'Moluk (Bilibo)',

  // Trælegetøj & nordisk design
  'Hape',
  'Janod',
  'Djeco',
  'Goki',
  'small foot',
  'Eichhorn',
  'Haba',
  "Grimm's",
  'Grapat',
  'PlanToys',
  'Bigjigs',
  'Tender Leaf Toys',
  'Vilac',
  "Kid's Concept",
  'Jabadabado',
  'By Astrup',

  // Baby & vuggestue
  'Fisher-Price',
  'Vtech',
  'Lamaze',
  'Little Dutch',
  'Sebra',
  'Konges Sløjd',
  'Filibabba',
  'Cam Cam Copenhagen',
  'Done by Deer',
  'Liewood',
  'Tryco',
  'Label Label',
  'BabyDan',
  'Tolo',

  // Dansk/skandinavisk plast & udendørs
  'Dantoy',
  'Plasto',
  'Magni',
  'Smallstuff',
  'Green Toys',
  'B. Toys',
  'Quercetti',
  'Lena',

  // Kreativitet, spil & bøger
  'Crayola',
  'Play-Doh',
  'Ravensburger',
  'Melissa & Doug',
  'Galt Toys',
  'SES Creative',
  'Aquabeads',
  'Hama (perler)',
  'Pixi bøger',
  'Squishmallows',
  'Tonies (Toniebox)',
  "Gabby's Dollhouse",
];

export const BRAND_OPTIONS = [
  { value: '', label: 'Intet varemærke' },
  ...TOY_BRANDS.sort((a, b) => a.localeCompare(b, 'da')).map(b => ({ value: b, label: b })),
];
