export const TOY_BRANDS = [
  'LEGO',
  'Playmobil',
  'Fisher-Price',
  'Mattel',
  'Hasbro',
  'Barbie',
  'Hot Wheels',
  'Schleich',
  'Bruder',
  'BRIO',
  'Haba',
  'Ravensburger',
  'Janod',
  'Melissa & Doug',
  'VTech',
  'LeapFrog',
  'Peg Perego',
  'Little Tikes',
  'Step2',
  'KidKraft',
  'Smoby',
  'Simba',
  'Dickie Toys',
  'Siku',
  'Märklin',
  'Rolf',
  'Micro Scooters',
  'Berg',
  'Kettler',
  'Puky',
  'Raleigh',
  'Chicco',
  'BabyBjörn',
  'Infantino',
  'Lamaze',
  'Tomy',
  'Vtech',
  'Leap Frog',
  'Orchard Toys',
  'Djeco',
  'Londji',
  'Eichhorn',
  'Bigjigs',
  'Plan Toys',
  'Hape',
  'Green Toys',
  'Magformers',
  'Magna-Tiles',
  'Geomag',
  'K\'Nex',
  'Meccano',
  'Mindstorms',
  'Warhammer',
  'Pokémon',
  'Yu-Gi-Oh!',
  'Magic: The Gathering',
  'Nerf',
  'Supersoaker',
  'Transformers',
  'Star Wars',
  'Marvel',
  'DC Comics',
  'Disney',
  'Frozen',
  'Minnie Mouse',
  'Mickey Mouse',
  'Paw Patrol',
  'Peppa Pig',
  'Bluey',
  'Cocomelon',
  'Sesame Street',
  'Thomas & Friends',
  'Postman Pat',
  'Bob the Builder',
  'Fireman Sam',
  'Teletubbies',
  'Trolls',
  'My Little Pony',
  'Care Bears',
  'Polly Pocket',
  'Monster High',
  'Enchantimals',
  'L.O.L. Surprise!',
  'Hatchimals',
  'Funko',
  'Ninjago',
  'Friends (LEGO)',
  'Duplo',
  'LEGO Technic',
  'LEGO City',
  'Playmobil City',
  'Playmobil Castle',
  'Brio World',
  'EverEarth',
  'Egmont Toys',
  'Moulin Roty',
  'Vilac',
  'Tender Leaf Toys',
  'Sago Mini',
  'Toniebox',
  'Yoto',
];

export const BRAND_OPTIONS = [
  { value: '', label: 'Ingen varemærke' },
  ...TOY_BRANDS.sort((a, b) => a.localeCompare(b, 'da')).map(b => ({ value: b, label: b })),
];
